apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue
  labels:
    app: hue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hue
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
        - name: hue-metastore
          image: james759426/hue:0.0.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "tail -f /dev/null" ]
          ports:
          - containerPort: 8888
